### ISSUE TITLE
RS485 controller circuit

### ISSUE THREAD

**Issue by MrReagle** [CarletonURocketry/avionics-hardware#3]
Implement RS485 circuit to communicate with nosecone:

Requirements
- Pick RS485 controller that can be controlled via UART I2C, or SPI (consult with Sam Dewan)
- RS485 line should be opto-isolated
- Create RS485 driver for the SAMD21 (software)
- Circuit will be implemented on nosecone board, and Connector board in main avionics bay. Circuit can be drawn as a **design block** in EAGLE

**Comment by samueldewan** [comment]
### SPI or UART?
We have a couple of options for an RS-485 transceiver. We could use a chip which connects to our microcontrollers via SPI and provides an integrated UART and RS-485 transceiver or we could connect to one of our microcontrollers UARTs and just use an RS-485 transceiver.

#### MAX3140
The [MAX3140](https://datasheets.maximintegrated.com/en/ds/MAX3140.pdf) is a chip which includes both a UART and a full duplex RS-285 transceiver. It connects to the microcontroller over SPI.

#### Standalone Transceiver
The other options is to use a standalone RS-485 transceiver. Note that many popular RS-485 transceiver parts require a 5 volt supply, it would probably be easier for us to use a part that could operate from a 3.3 volt supply (for example the [SN65HVD12](https://www.ti.com/lit/ds/sgls278e/sgls278e.pdf) or [SN65HVD73](http://www.ti.com/lit/ds/symlink/sn65hvd73.pdf)).

### Full or Half Duplex?
Another thing that needs to be considered is whether we should use full or half duplex communication. Either of the options above could be used for either type of connection. Full duplex communication would be easier to implement from a software perspective, but would require two twisted pairs running to the nose cone. A half duplex connection would probably be cheaper and easer to implement in hardware but would necessitate more complex software.
